### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1652]
Explicit support for .NET 6. 

- [x] Ensure the `FluentValidation.AspNetCore` package works correctly on .NET 6
- [x] Update the integration test project
- [x] Update the required SDK version in global.json
- [x] Update CI to install preview SDK versions
- [x] Should work with both FluentValidation 10.x and FluentValidation 9.x

Development for this will not begin until .NET 6 previews are more stable, later in the year (probably preview 5). 

*Note*: assuming no breaking changes are made to .NET 6's validation infrastructure, the .net 5 builds of FV will work fine. This issue is primarily to track the addition of our .net 6 integration tests.

**Comment by zoinkydoink** [comment]
Any idea when this is going to get tackled? we are already at preview 3, thank you

**Comment by JeremySkinner** [comment]
Probably in a couple of months. Usually I wait until around preview 5/6/7 as there’s usually too much churn before then. 

That being said, the net5 binaries should work fine on net6, provided they haven’t made any breaking changes to the aspnet validation apis.

**Comment by JeremySkinner** [comment]
That isn’t related to .net6. That’d because the Blazor component you’re using hasn’t been updated to work with FluentValidation 10.0. You’ll either need to use fluentValidation 9.x or wait for the integration component to be updated to FV 10.

**Comment by JeremySkinner** [comment]
Actually they’ve released an update that fixes it already - upgrading to Accelist.FluentValidation.Blazor 2.1.0 should fix that

**Comment by zoinkydoink** [comment]
Ya i will talk to them, I am using latest version of their control 4.0, I will first downgrade to fluent 9.x and see if that still has an issue, if it does than it means its got something to do with .net 6, then I will circle back with them.
Thanks Jeremy

**Comment by JeremySkinner** [comment]
Attempting to run the integraiton tests against preview 6 generates the following build errors currently: 

```
CSC : error CS0006: Metadata file '/home/jskinner/.nuget/packages/microsoft.extensions.logging.abstractions/3.1.0/analyzers/dotnet/cs/Microsoft.Extensions.Logging.Generators.dll' could not be found [/home/jskinner/code/FluentValidation/src/FluentValidation.Tests.AspNetCore/FluentValidation.Tests.AspNetCore.csproj]
CSC : error CS0006: Metadata file '/home/jskinner/.nuget/packages/system.text.json/4.7.0/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll' could not be found [/home/jskinner/code/FluentValidation/src/FluentValidation.Tests.AspNetCore/FluentValidation.Tests.AspNetCore.csproj]
```

I haven't had time to look into why, but something's changed in the .net6 sdk

**Comment by JeremySkinner** [comment]
Secondary issue: https://github.com/dotnet/aspnetcore/issues/34354 The `WebApplicationFactory` we use for integration tests has a regression in .net 6.

**Comment by JeremySkinner** [comment]
Updated to preview 7 and everything still works correctly. The workaround from https://github.com/dotnet/sdk/issues/18148#issuecomment-860957180 is no longer necessary, although https://github.com/dotnet/aspnetcore/issues/34354 still is.

**Comment by JeremySkinner** [comment]
https://github.com/FluentValidation/FluentValidation/pull/1783
